# Generated by Django 4.2.11 on 2026-05-16 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=50)),
                ('tamanho', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=50)),
                ('codigo_barras', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('BIPADO', 'Bipado'), ('PULADO', 'Pulado'), ('DANIFICADO', 'Danificado')], default='PENDENTE', max_length=20)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'item_pedido',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=50, unique=True)),
                ('cliente', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_PICKING', 'Em Picking'), ('PARCIAL', 'Parcial'), ('FINALIZADO', 'Finalizado')], default='ABERTO', max_length=20)),
                ('total_pecas', models.IntegerField(default=0)),
                ('peso_bruto', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='SessaoPicking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pecas_bipadas', models.IntegerField(default=0)),
                ('erros', models.IntegerField(default=0)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('ativa', models.BooleanField(default=True)),
                ('colaborador', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.usuario')),
                ('item_atual', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='picking_engine.itempedido')),
                ('pedido', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='picking_engine.pedido')),
            ],
            options={
                'db_table': 'sessao_picking',
            },
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='picking_engine.pedido'),
        ),
    ]
