# Generated by Django 4.2.11 on 2026-05-16 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_usuario_supervisor_resp_logauditoriausuario'),
        ('picking_engine', '0002_webhooks_kpis_heartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpidefinicao',
            name='supervisor_resp',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'perfil': 'SUPERVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.usuario'),
        ),
        migrations.CreateModel(
            name='LogAgingStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=100)),
                ('acao', models.CharField(choices=[('REMOVIDO', 'Removido / Baixa Manual'), ('ATRIBUIDO', 'Atribuído ao Supervisor'), ('RESOLVIDO', 'Resolvido pelo Supervisor')], max_length=20)),
                ('motivo', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aging_resolvidos', to='authentication.usuario')),
                ('supervisor_resp', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aging_atribuidos', to='authentication.usuario')),
            ],
            options={
                'db_table': 'log_aging_stock',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='ExcecaoPicking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_operador', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('AUTORIZADO', 'Autorizado'), ('NEGADO', 'Negado')], default='PENDENTE', max_length=20)),
                ('justificativa_supervisor', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='picking_engine.itempedido')),
                ('sessao', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='excecoes', to='picking_engine.sessaopicking')),
                ('supervisor_resp', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.usuario')),
            ],
            options={
                'db_table': 'excecao_picking',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
