# Generated by Django 4.2.11 on 2026-05-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picking_engine', '0003_kpidefinicao_supervisor_resp_logagingstock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_pph', models.IntegerField(default=130)),
                ('meta_caixas', models.IntegerField(default=300)),
                ('meta_acuracia', models.IntegerField(default=99)),
                ('meta_streak', models.IntegerField(default=10)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meta_global',
            },
        ),
        migrations.AlterModelOptions(
            name='kpidefinicao',
            options={'ordering': ['-favorito', 'nome']},
        ),
        migrations.AddField(
            model_name='kpidefinicao',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
