# Generated by Django 6.0.5 on 2026-05-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cracha', models.CharField(max_length=50, unique=True)),
                ('perfil', models.CharField(choices=[('COLABORADOR', 'Colaborador'), ('SUPERVISOR', 'Supervisor'), ('ADM', 'Administrador')], max_length=20)),
                ('login_status', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
