# Generated by Django 4.2.11 on 2026-05-16 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usuario_campos_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='supervisor_resp',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'perfil': 'SUPERVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe_supervisionada', to='authentication.usuario'),
        ),
        migrations.CreateModel(
            name='LogAuditoriaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIADO', 'Criado'), ('MODIFICADO', 'Modificado'), ('EXCLUIDO', 'Excluído/Demitido'), ('ATRIBUIDO', 'Atribuído a Equipe')], max_length=20)),
                ('detalhes', models.TextField(blank=True, default='')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_gerados', to='authentication.usuario')),
                ('usuario_alvo', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='logs_recebidos', to='authentication.usuario')),
            ],
            options={
                'db_table': 'log_auditoria_usuario',
                'ordering': ['-data_hora'],
            },
        ),
    ]
