# Generated by Django 4.2.11 on 2026-05-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_usuario_supervisor_resp_logauditoriausuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
